[WIP] Azure blob storage integration
thelastpickle/cassandra-medusa pull request #219
Opened 2020-10-23 00:36 UTC by ilhanadiyaman

Fixes #171

2020-10-23 06:47 UTC, adejanovski commented
Hi @ilhanadiyaman,

thanks for bringing Azure storage support to Medusa!
Libcloud sadly isn't yet able to reliably and quickly upload very large files. For S3 we rely on awscli to handle large files (>100MB) uploads/downloads and for GCP we use gsutil.
I see that Azure has [its own cli](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-cli) which I think we'll need to use here as well. You could copy the S3 implementation for Azure as a starting point since gsutil has a funny way of getting its inputs...

I'll be happy to help you as much as I can.

Let me know what you think.

2020-10-23 08:26 UTC, ilhanadiyaman commented
Hi @adejanovski,

I didn't know about libcloud reliability for large files. Thanks for letting me know, otherwise I was going to start using it on our cassandra cluster. :) I'll check what I can do with azure cli and let you know.

This work is still in progress. I'd like add some documentation and integration tips. Also, how can we add azure blob storage to CI/CD checks? I already add azure to the integration tests.

2020-10-23 08:51 UTC, arodrime commented
Oh I'm late to the party: https://github.com/thelastpickle/cassandra-medusa/issues/171#issuecomment-715199497

@adejanovski is just too quick for me! :)

2020-10-23 09:21 UTC, ilhanadiyaman commented
I didn't know either @adejanovski will look for the PR that fast. That's why I only let you @arodrime know last night :) But it's good to know that issue regarding large files. I'll check and let you guys know.

2020-10-26 19:43 UTC, ilhanadiyaman commented
I just pushed the new commits regarding documentation and azcli implementation. During the testing, I increase the row numbers to be inserted to 10M in the first scenario so that the file size gets larger than 64MB. It took a lot of time for ccm to insert the rows but at least it didn't fail. If there are other way to test it, please let me know.

There is one thing to mention, S3 and GCS uses eTag header to return MD5 file hashes. While in Azure, eTag looks like a hex  which is calculated based on last modified time. When we reupload same files, these "eTag" hashes are changing which causes failure on validating the manifest. Therefore, I had to use another property which is called "CONTENT-MD5". 

Let me know what you think @adejanovski and @arodrime.

2020-11-02 13:19 UTC, adejanovski requested changes
Hi @ilhanadiyaman,

this is an awesome addition to Medusa, thanks a lot for pushing this PR.
There are a few places where the current implementation is broken and I've added suggestions which I tested locally with the integration tests.
Once you've applied the fixes (or implemented yours), could you please:
- Add the following entry at the top of CHANGELOG.md :
```
### 0.8.0 (TBD)
- Add Azure blob storage support (@ilhanadiyaman)
```
- squash all the commits into a single one

I'll do one last check and run the integration tests before merging once you've forced push those changes.

Thanks again!

2020-11-02 13:19 UTC, adejanovski commented on medusa/storage/azure_blobs_storage/azcli.py
> +        cmd = [self._az_cli_path, "storage", "blob", "download", "-f", str(dest), "-c", bucket_name, "-n", src]
```suggestion
        cmd = [self._az_cli_path, "storage", "blob", "download", "-f", os.path.join(str(dest), str(src).split("/")[-1]), "-c", bucket_name, "-n", src]
```

The typo fix from `downlod_blobs` to `download_blobs` along with making multi part upload threshold configurable made this code path testable during integration tests.
It fails consistently with the following error:
```
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[Errno 21] Is a directory: '/tmp/medusa-download-all-tables/system_auth/roles-5bc52802de2535edaeab188eecebb090/'
Traceback (most recent call last):
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 709, in _run_job
    cmd_copy.exception_handler(ex)
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 341, in new_handler
    raise ex
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/Users/adejanovski/projets/cassandra/thelastpickle/py36/lib/python3.6/site-packages/azure/multiapi/storage/v2018_11_09/blob/baseblobservice.py", line 1968, in get_blob_to_path
    with open(file_path, open_mode) as stream:
IsADirectoryError: [Errno 21] Is a directory: '/tmp/medusa-download-all-tables/system_auth/roles-5bc52802de2535edaeab188eecebb090/'
To open an issue, please run: 'az feedback'
```

Apparently the destination path must contain the file name and not just the destination directory name.
With the above suggestion, integration tests are passing.

2020-11-02 13:19 UTC, adejanovski commented on tests/integration/features/steps/integration_steps.py
> +            "prefix": storage_prefix
```suggestion
            "multi_part_upload_threshold": 1 * 1024,
            "prefix": storage_prefix
```

This allows to use multipart uploads for files >= 1kB, which makes integration tests use both upload methods.

2020-11-06 19:04 UTC, ilhanadiyaman commented
Sorry my late response @adejanovski. Thanks for your review and suggestions. Next week, I'll review all of them and send a PR as you suggested.

2020-11-18 15:21 UTC, ilhanadiyaman commented on medusa/storage/azure_storage.py
> +    def downlod_blobs(self, srcs, dest):
Silly mistake. Nice catch!

2020-11-18 15:23 UTC, ilhanadiyaman commented on medusa/storage/azure_blobs_storage/concurrent.py
> +MULTI_PART_UPLOAD_THRESHOLD = 64 * 1024 * 1024
Alright. I'll add the threshold configuration like S3.

2020-11-23 01:54 UTC, ilhanadiyaman commented
Fixed all linter errors. Integration tests are passing. Hopefully, we can ship this one @adejanovski.

2020-11-24 08:48 UTC, adejanovski commented
Awesome work @ilhanadiyaman!!

Thanks a lot for adding Azure storage support to Medusa.
I merged your changes from the command line as I needed to fix three minor issues (here's [the commit](https://github.com/thelastpickle/cassandra-medusa/commit/983234acc1b4e6bf50ff459b61ca7e667ceaef69)):

- Rebase on top of `master`
- Update setup.py to allow installing Azure optional dependencies: `sudo pip install cassandra-medusa[AZURE]`
- Remove the unused threshold constant in `storage/azure_blobs_storage/concurrent.py`

Thanks again!

2020-11-24 08:48 UTC, closed without merging