Allow to download only a set of keyspaces/tables
thelastpickle/cassandra-medusa pull request #221
Opened 2020-10-23 18:24 UTC by masterzen

The `medusa download` command allows only to download a whole backup.

This change adds the same filtering flags as the `restore-node` command:
--keyspace <ks>
--table <ks.ta>

This allows to specify which tables or keyspaces combinations medusa will download from the storage.

By default, `medusa download` always downloads the system keyspaces. I added a new option,
`--ignore-system-keyspaces` that allows to not download them. This is very useful if you just want to download a specific keyspace or table.

I noticed that `medusa download` always creates unnecessary local directories (one per keyspace). When downloading only some keyspaces or specific tables, there's no reason all the other keyspaces directory needs to be created. I modified this behavior to only create the downloaded keyspaces directories.

2020-10-26 14:26 UTC, masterzen commented
I fixed the integration test failure, except the last one for which I'm a bit puzzled.

Note that the gcs and s3 test variant don't do anything in PRs (I suppose it's made to limit cost).

2020-11-10 06:24 UTC, adejanovski commented on medusa/filtering.py
> +# Copyright 2019 Spotify AB. All rights reserved.
@michaelsembwever, which copyright should be added here?
Definitely not the Spotify one, but I'm wondering what's our approach for external contributions.

I like the approach described [here](https://www.linuxfoundation.org/blog/2020/01/copyright-notices-in-open-source-software-projects/), under "Community best practices". 
wdyt?

2020-11-10 06:32 UTC, adejanovski requested changes
LGTM aside from a minor comment on the code and some questions we need to answer on copyrights.

2020-11-10 06:32 UTC, adejanovski commented on medusa/filtering.py
> +        if ks in keep_keyspaces or (not ignore_system_keyspaces and (ks in SYSTEM_KEYSPACES)):
Would you mind extracting this condition into a separate method? It's a little hard to read.

2020-11-20 13:00 UTC, adejanovski commented
Hi @masterzen,

Let me know if you need help moving this PR forward.

Thanks!

2020-11-20 13:11 UTC, masterzen commented
@adejanovski, sorry I was quite busy those last weeks. I'll hope to be able to fix the issues you pointed in your comments ASAP.

BTW, did you had an answer about the copyright ?

I'm personally fine with the approach you linked, using something like "Copyright Contributors to the Cassandra Medusa project"

Also, I need to understand why the last integration tests doesn't pass. It apparently errors when calling `sstableloader`.

And finally, I'm not sure it is normal, but the GCS and S3 integration tests never do anything in the PR.

2020-11-20 13:56 UTC, adejanovski commented
Sure thing, no worries.

For the copyright, would you mind adding the Datastax copyright?

```
# Copyright 2020 DataStax Inc.
```

You still hold copyright to your contribution, which is tracked by GitHub, but gives Datastax permission to donate the code to the ASF for example or legally defend/protect it.

The failing integration tests have been fixed in `master` and in Cassandra itself, there's no relation to your PR.
The GCS and S3 integration tests use GitHub Actions secrets to get credentials for GCP and AWS, which are not available to PRs coming from external contribution for security reasons.
These tests will always be skipped in this case, and that's an expected behavior.

2020-11-20 13:56 UTC, adejanovski commented
You'll need to rebase anyway due to conflicts on `medusa/download.py`, which will make your PR pass all integration tests.

2020-11-23 18:32 UTC, masterzen commented
@adejanovski, I've pushed a new version that took into account your comments.

Regarding the copyright, I left the Spotify one, because most of that code was extracted from a file that had this copyright.

Let me know if you need anything else.
Thanks !

2020-12-22 15:09 UTC, adejanovski approved these changes

2020-12-22 15:09 UTC, merged