Backup and DeleteBackup do not return error code
thelastpickle/cassandra-medusa pull request #265
Opened 2021-01-27 17:30 UTC by burmanm

In case of Exception, Backup and DeleteBackup methods in the gRPC should return an error code. Fixes https://github.com/k8ssandra/k8ssandra/issues/256

2021-01-27 17:34 UTC, adejanovski requested changes
LGTM.

Would you mind adding a test for this? 
Scenario 16 of the integration tests could be reused as a base to generate a failing backup and test the return code.
Thanks!

2021-01-27 17:37 UTC, jsanda commented
I will manually test this in k8ssandra and report back my results.

2021-01-27 18:03 UTC, jsanda commented
The changes look good. I reported my results in https://github.com/k8ssandra/k8ssandra/issues/256.

@burmanm after you add the integration test and this PR is merged, we will need to update the Medusa image in k8ssandra before we can close out https://github.com/k8ssandra/k8ssandra/issues/256.

2021-01-28 13:43 UTC, adejanovski approved these changes
Thanks for adding the tests @burmanm !

LGTM

2021-01-28 14:24 UTC, merged