Add s3_compatible storage option for all S3 compatible storage targets
thelastpickle/cassandra-medusa pull request #283
Opened 2021-02-09 07:55 UTC by burmanm

Further consolidation of the code, s3_compatible is the new s3 compatible storage driver

Fix some bugs, typos and make the s3_compat load credentials with the aws keys (for compatibility)

Address comments, add http/https differentation to endpoint_url generation

Remove is_azure from Azure blobs storage as backup_node does not need it
(if threshold is set, it will be used)

(cherry picked from commit 544940dda0463df7e062113ad498345fa97a5955)

2021-02-09 07:55 UTC, burmanm commented
This is the version for the CI runs.

2021-02-09 16:04 UTC, adejanovski requested changes
The IBM storage tests are currently failing due to how you try to override `config.host`. 
I think we should drop the specific bits for the IBM storage backend and fully rely on the new S3 generic class, removing the host/region IBM mapping which uses a hardcoded list anyway (that's on me).
Let's still identify `ibm` as a valid storage provider and use the `S3BaseStorage` class for it directly like it's done for `s3_compatible`.

2021-02-09 16:04 UTC, adejanovski commented on medusa/storage/s3_storage.py
>      S3_AP_NORTHEAST = 's3_ap_northeast'
We should remove these in favor of using `s3` as storage provider and setting the region instead of using region specific storage providers.

2021-02-09 16:04 UTC, adejanovski commented on medusa/storage/ibm_storage.py
> +            self.config.host = IBM_CLOUD_HOSTS_BY_REGION[self.config.region]
You cannot change a config element like this. But I think we should drop this static mapping and let the user fill in the host and region in config.

2021-02-11 09:26 UTC, adejanovski approved these changes

2021-02-11 09:26 UTC, merged