Set TTL for storage connections
thelastpickle/cassandra-medusa pull request #412
Opened 2021-10-06 11:29 UTC by ivanmp91

This should fix the issues for long running backups using temporary credentials (like AWS IAM role). Right now the problem is those connections are never recycled, and if a backup is running longer than the credentials expiration time, it'll just fail.
This PR set a max TTL for those connections of 20 minutes (it's just an arbitrary number, but should be good enough) and after this period of time, it just resets the connection pool forcing to create new fresh connections.

2021-11-16 06:55 UTC, adejanovski commented
Hi @ivanmp91,

if I remember our chat correctly, we said that this wouldn't fully fix the issue as the main connection to the storage backend would have the same issue.
Wasn't that correct? Did you conduct tests that allowed you to verify your patch actually fixes the issue in production?

2021-11-16 10:18 UTC, ivanmp91 commented
> if I remember our chat correctly, we said that this wouldn't fully fix the issue as the main connection to the storage backend would have the same issue. Wasn't that correct?

We talked about two solutions:

- Reimplement the [get_blob](https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/s3_compat_storage/awscli.py#L174) method to use aws cli instead. The main problem is that other storage connector would still have the same issue and also it wouldn't get the metadata needed.

- Refresh the credentials keys over the time from the storage connection pool. This is what's implemented in this PR and it fixes the issue where long backups (in the case of relying on AWS IAM role around 6-7 hours) it will start failing because the connection pool is still reusing connections with old keys. Forcing those connections to be refreshed over the time it will prevent to ever use expired credentials and fully fix this issue. Actually in our case the workaround has been to increase the number of threads to make sure the backup is done in less than the credentials expiration time.

>Did you conduct tests that allowed you to verify your patch actually fixes the issue in production?

I haven't tried it in production, but I can do a test with a large data node and make sure the backup takes more than the credentials expiration time to see if it completes successfully. I'll reply back with the results when this is done.

2022-02-19 20:20 UTC, ivanmp91 commented
@adejanovski sorry it took so long, but finally I've been able to test performing a full backup with the changes introduced in this PR and it worked like a charm at the first attempt without any errors. So it looks like this fixes the issue reported initially in the PR and refreshing the connection pool over time makes the trick:

```
[2022-02-18 22:42:15,858] INFO: Updating backup index
[2022-02-18 22:42:17,965] INFO: Backup done
[2022-02-18 22:42:17,966] INFO: - Started: 2022-02-18 16:48:35
                        - Started extracting data: 2022-02-18 16:49:47
                        - Finished: 2022-02-18 22:42:17
[2022-02-18 22:42:17,966] INFO: - Real duration: 5:52:30.761670 (excludes time waiting for other nodes)
[2022-02-18 22:42:18,054] INFO: - 58376 files, 1.06 TB
[2022-02-18 22:42:18,054] INFO: - 58376 files copied from host
[2022-02-18 22:42:18,139] INFO: Updated from existing status: 0 to new status: 1 for backup id: ivan-test
```

2022-02-23 05:41 UTC, adejanovski commented on medusa/storage/concurrent.py
> +                self.timer = time.time()
Would you mind adding some comments to explain what you're doing here?

2022-02-23 05:44 UTC, adejanovski requested changes
I just have a minor request for comments in the code, and thanks a lot for making those tests after all this time.

2022-02-23 05:44 UTC, adejanovski commented on medusa/storage/s3_compat_storage/concurrent.py
> +                self.timer = time.time()
Same request here, a comment would be nice.

2022-03-22 13:23 UTC, merged