Make a tempfile while backup is running
thelastpickle/cassandra-medusa pull request #731
Opened 2024-03-25 13:43 UTC by rzvoncek

2024-03-28 07:33 UTC, adejanovski requested changes

2024-03-29 10:49 UTC, adejanovski commented
I don't know if it's related to changes in this PR but I'm seeing the following errors in the logs:

```
[2024-03-29 09:42:13,612] INFO: Recording async backup information.
[2024-03-29 09:42:13,612] ERROR: Failed to record backup information executed in async manner. Error: too many values to unpack (expected 8)
```

and:

```
[2024-03-29 09:32:12,494] INFO: Recording async backup information.
[2024-03-29 09:32:12,495] ERROR: Exception in callback record_backup_info(<Future cancelled>) at /home/cassandra/medusa/service/grpc/server.py:346
handle: <Handle record_backup_info(<Future cancelled>) at /home/cassandra/medusa/service/grpc/server.py:346>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/cassandra/medusa/service/grpc/server.py", line 349, in record_backup_info
    if future.exception():
asyncio.exceptions.CancelledError: Removal of backup requested. Cancelling backup Name: medusa-backup8 with done state: False
```

2024-04-01 09:21 UTC, rzvoncek commented
Thanks for catching those, I've pushed a fix.

2024-04-15 08:52 UTC, adejanovski approved these changes

2024-04-15 08:54 UTC, merged