Add option to prefer incomplete backups when doing a purge
thelastpickle/cassandra-medusa pull request #732
Opened 2024-03-28 14:59 UTC by rzvoncek

2024-03-29 10:44 UTC, adejanovski requested changes
I'm a little confused with this implementation and how it drifts from what was originally asked in the ticket.
Let's connect to chat about this.

2024-03-29 10:44 UTC, adejanovski commented on medusa/medusacli.py
> +              help='Prioritise incomplete backups when purging by count')
**Question:** in which case do you think we may prefer to keep incomplete backups? They cannot be restored anyway so it doesn't seem like something we'd want to keep.

2024-03-29 10:44 UTC, adejanovski commented on medusa/purge.py
> +    backups_to_purge |= set(backups_to_purge_by_age(node_backups, max_backup_age))
**Question:** So we're considering that incomplete backups shouldn't be affected by the new purge priorities that we're setting? How is that purge rule different than the purge by count rule?

2024-03-29 10:44 UTC, adejanovski commented on medusa/purge.py
> +        backups_to_purge |= set(backups_to_purge_by_count(node_backups, max_backup_count))
**Issue:** Unless I'm missing something, I think this is doing the opposite of what was requested in the ticket.
If we don't prefer incomplete backups (which should mean we prefer complete backups?), then you're applying the same rules as before here, which can lead to having only incomplete backups left after the purge.
The implementation we're looking for here is to purge incomplete backups first (disregarding their age and count) and only then apply the age/count purge rules.

I think we could widely simplify this code and the rules by always purging incomplete backups in priority, and only then apply the purge rules.
wdyt?

2024-06-06 05:52 UTC, adejanovski commented
Bump @rzvoncek 👋

2024-06-13 14:18 UTC, rzvoncek commented
Closing in favour of https://github.com/thelastpickle/cassandra-medusa/pull/778

2024-06-13 14:18 UTC, closed without merging