Support (S3, GCP, Azure) storage classes
thelastpickle/cassandra-medusa pull request #737
Opened 2024-04-07 18:44 UTC by mohammad-aburadeh

Medusa does not support specifying the storage class name when uploading backups to S3/GCP/Azure.
This is very important for many customers as it can help to reduce the storage cost.

Closes #568

2024-04-22 10:39 UTC, rzvoncek requested changes
Hello @mohammad-aburadeh and sorry to keep you waiting for so long. I've finally managed to have a proper look at this and tried to test it out. Sadly, I have bad news.

In the context of S3, we need to limit the sotrage classes we support. It doesn't seem to be possible to read from Glacier and below, so we should not let Medusa write those because it won't be able to read after itself.

In the context of GCS, the explicit storage classes don't seem to work at all. The header seems just ignored. I didn't find a way to do this aside from setting a default value on the entire bucket.

In the context of Azure, we need to pass enums, not strings, because that's what the client we use expects.

Because of this, I'm sorry to return the PR to you and kindly ask you to do one more iteration to fix/improve things.

2024-04-22 10:39 UTC, rzvoncek commented on medusa/storage/google_storage.py
> +            headers=ex_header,
I could not get this to work with GCS. All the uploads I did ended up with the Standard storage class. Swithich the default bucket storage class mode to `Managed with Autoclass` did not help either.

It's like the GCS ignores the HTTP header. Even if I set it in the request, the response comes with ` 'storageClass': 'STANDARD',`

2024-04-22 10:39 UTC, rzvoncek commented on medusa-example.ini
> +; AWS S3 Storage classes: STANDARD | REDUCED_REDUNDANCY | STANDARD_IA | ONEZONE_IA | INTELLIGENT_TIERING | GLACIER | DEEP_ARCHIVE | GLACIER_IR
Starting from `GLACIER`, things start to break.
The issue is that we can upload stuff with this storage class, but the we try to read stuff back, and we cannot . At least not in the current implementation.
I think the easy way out is to simply not support the 3 lowest tiers. We 'd need to document this somewhere, and then add checks in the config.py to not allow specifying these.

2024-04-22 10:39 UTC, rzvoncek commented on medusa/storage/azure_storage.py
> +            standard_blob_tier=self.get_storage_class(),
I'm sorry but this does not work. The Azure library needs to have the instances of `StandardBlobTier` clsss (which are just an enum) here.
So we need to do two things:
- on line 28 import the class (`from azure.storage.blob import BlobProperties, StandardBlobTier`)
- map the config values to the values of the enum and pass the whole enum (down the call stack, the library does call `.value()` on the enum.

2024-05-20 08:48 UTC, federicobaldo commented
hi everyone, any help needed here? this feature is very interesting and would like to try using it ASAP

2024-05-22 10:26 UTC, kantipudipythian commented
Hi,
We tried the following steps to add the storage_class. We are using AWS S3 bucket for storing the backup files.

1. Upgraded the Medusa version to 0.21.0 from 0.17.2.
2. Added the storage_class parameter to the medusa.ini file.
3. We updated config.py, abstract_storage.py, s3_base_storage.py files accordingly.
4. Ran differential backup.

The backup was successful. But it is taking 1 hour to complete. The previous backups would finish within 2-5minutes. We observed that the manifest.json file is taking more time. Can you please let us know what might be the issue?

2024-06-12 13:52 UTC, rzvoncek commented
I've implemented the suggested changes and added integration tests over at https://github.com/thelastpickle/cassandra-medusa/pull/777/checks

2024-06-12 13:52 UTC, closed without merging

2024-06-20 12:30 UTC, kantipudipythian commented
Hi,

Below are the tests done on the cluster:

Old Medusa Version: 0.17.2
New Medusa Version: 0.21.0
Storage_class: STANDARD_IA

Test1 (New Medusa version):
New bucket,
storage_class parameter in the medusa.ini file
Started backup.
The 2nd backup took the same time as the first backup around 50 minutes.

Test2 (old Medusa version):
New bucket,
storage_class parameter in the medusa.ini file
Started backup.
The backup was successful, 1st backup took 50 minutes to complete. The 2nd backup was done within 1minute.

Test3 (old Medusa version):
New bucket,
storage_class parameter in the medusa.ini file
Modified config.py, abstract_storage.py, s3_base_storage.py 
Started backup.
The backup was successful, 1st backup took 6 minutes to complete. The 2nd backup was done within 1minute. (There are few backups in the bucket while taking this backup.)

Test4 (old Medusa version):
New bucket,
storage_class parameter in the medusa.ini file
Modified config.py, abstract_storage.py, s3_base_storage.py 
Started backup with the empty new bucket.
The backup was successful, 1st backup took 50mins to complete. The 2nd backup was done within 1minute.

Can you please let us know why the New Medusa version with STANDARD_IA is taking more time?

Thanks,
Kanthi Rekha.